### ISSUE TITLE
[Documentation] Check Composer test command

### ISSUE THREAD

**Issue by Luan-vP** [inblockio/DataAccounting#101]
Current REAMDE.me says 
`compose` test

^ not a command

If I run `composer test` I get the following error:

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "test" is not defined.

**Comment by rht** [comment]
The composer.json used to be working, because this repo started from https://github.com/wikimedia/mediawiki-extensions-BoilerPlate.

And then the relevant test specification was deleted in https://github.com/FantasticoFox/DataAccounting/commit/01d923dc76b3e000bc36e8cb31171fb25ceddc61#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34.

We should add it back.

**Comment by rht** [comment]
Wrong wikimedia repo! I meant https://github.com/wikimedia/mediawiki-extensions-examples.

**Comment by FantasticoFox** [comment]
[Documentation]

**Comment by FantasticoFox** [comment]
Will be solved between 14.Nov - 16.Nov
