### ISSUE TITLE
Changed settings are not applied after deployment by MediaWiki:MainPage and MediaWiki:Tweeki-navbar-class

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#203]
MediaWiki: <settings> pages seem not to be loaded until visited by the user.
How do we get settings stored there to be applied after redeploy?

**Comment by FantasticoFox** [comment]
solution proposal:
rht: curl pages during setup

**Comment by FantasticoFox** [comment]
in aqua/install...
# Tweeki Skin: This loads the settings from a custom set value
curl -s "$PKC_SERVER/index.php/MediaWiki:Tweeki-navbar-right"

# Set modified path of Main_Page if applicable
curl -s "$PKC_SERVER/index.php/MediaWiki:Mainpage"

**Comment by FantasticoFox** [comment]
We hacked it with the curl ... whats your recommendation @it-spiderman is there a general way to solve this?

**Comment by FantasticoFox** [comment]
The curl hack does not work if the wiki is set to private as the curl as no permission...

**Comment by rht** [comment]
To test it without the curl, hack, uncomment https://github.com/inblockio/micro-PKC/blob/8f8c6eebc78177db56d33a1d27251051ef682b28/aqua/install_pkc.sh#L186 and run `./pkc setup`. The navbar color would be errorneously white instead of black (if it is black, then the custom Tweeki stuff is properly loaded).

**Comment by it-spiderman** [comment]
Tweeki uses MW i18n system as configuration, which is not good, but i guess it will work.
You override the messages by editing the message page, but im guessing that does not refresh the cache in time. So, when you request the page it forces the cache update. I nuked and rerun the setup seveal times, without the curl command, but never faced the issue.
Solutions:
- run `php maintenance/rebuildLocalisationCache.php --lang=en --force` (cannot say if it will work, since i could not reproduce it)
- override it in code (proper solution, but requires another extension, or even better you own skin that extends Tweeki)

**Comment by rht** [comment]
I think the path that requires the least effort is to replace the curl hack with `maintenance/rebuildLocalisationCache.php`.

**Comment by it-spiderman** [comment]
yes, that is (if it works) a pretty good solution, not even hacky, as some people recommend doing this after installation anyways
Did you test it already?

**Comment by FantasticoFox** [comment]
Good. Closing the issue then. Thanks!

**Comment by rht** [comment]
Does that mean you wasn't able to reproduce it either? So I think what was happening that you know manually editing those pages from the web UI doesn't cause an update? And then we simply assume that editing from the command line would have the problem as well? If so I am removing the curl step now.

**Comment by rht** [comment]
See https://github.com/inblockio/micro-PKC/commit/30ae150361a647be514a16ec68b30b951135fb88.
