### ISSUE TITLE
Page with "/" in the title can't be verified.

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/DataAccounting#260]
![image](https://user-images.githubusercontent.com/45313235/148328841-2f052af7-2977-482a-9e17-246751ec198f.png)

**Comment by FantasticoFox** [comment]
We migrated away for the interim usage with ':' which works fine so not so important to fix right now.
':' also represents namespace in MW which is better actually...

**Comment by rht** [comment]
This is probably because of the REST route pattern matcher in extension.json mistakenly assumes the '/' to be a path separator, e.g. `"path": "/data_accounting/get_hash_chain_info/title/{page_title}",`. The solution is to switch to URL param. We definitely need to solve this, because I tested that http://localhost:9352/index.php/Foo/bar works.

**Comment by FantasticoFox** [comment]
FIXED in https://github.com/inblockio/DataAccounting/pull/279
